language: go

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.16.5"

before_install:  # generate any other needed files
  - go generate ./...
  - find . -name '*.go' -exec gofmt -w {} \;
  
before_script:
  - go vet ./...
  - git diff
  - diff -u <(echo -n) <(gofmt -d .)

after_success:  # run benchmarks
  - go test -v -bench . -run ^$ ./...
